version: "3"

services:
  backend:
    build:
      context: ./elevators-service
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./elevators-ui
    ports:
      - "4200:80"
    depends_on:
      - backend